### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'red')

### ISSUE THREAD

**Issue by ModProg** [cpiber/NebulaEnhance#35]
Error when trying to build

Running `npm run start:firefox` yields
```console
> nebulaenhance@1.1.6 start:firefox
> [ -d extension-dist ] || npm run build:light && concurrently "npm:start" "npm:ext:firefox"


> nebulaenhance@1.1.6 build:light
> rollup -c --configType all

[!] TypeError: Cannot read properties of undefined (reading 'red')
TypeError: Cannot read properties of undefined (reading 'red')
    at default (file:///NebulaEnhance/rollup.config.mjs:258:31)
    at getConfigList (/NebulaEnhance/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/loadConfigFile.js:640:11)
    at loadConfigFile (/NebulaEnhance/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/loadConfigFile.js:568:12)
    at Object.loadAndParseConfigFile (/NebulaEnhance/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/loadConfigFile.js:544:21)
    at getConfigs (/NebulaEnhance/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/bin/rollup:1691:39)
    at runRollup (/NebulaEnhance/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/bin/rollup:1665:43)
```

**Comment by cpiber** [comment]
That appears to be the line `console.warn(chalk.stderr.red.bold`YouTube API key empty!`);`. Looks like `chalk` can't bind to colors on stderr. I would rather recommend you run `npm run start` and `npm run ext:firefox` in two separate terminals, that might work better, I haven't used that target in a long time.

You can try commenting out that line, it's just a warning. It's telling you that you need to specify a YouTube API key, which is required for searching videos (Nebula -> YouTube).

**Comment by ModProg** [comment]
commenting that line out fixed it.
